<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Criar</name>
   <tag></tag>
   <elementGuidId>d003d4f1-5497-4f40-ab01-4220eb067f9b</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;empresa-list-actions-create&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#empresa-list-actions-create</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'empresa-list-actions-create' and @title = 'Criar' and (text() = 'Criar ' or . = 'Criar ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e94c57ca-d9d8-4052-abda-b2e416eb4139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a4c5ddca-0be5-4208-9f6f-5b0750da8712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ndd-ng-actionbar__action__item-btn</value>
      <webElementGuid>09b0bc46-fcba-422d-827d-ac8c31d73919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empresa-list-actions-create</value>
      <webElementGuid>f2fcb970-0ddb-4d42-9da8-20335bd8d77d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Criar</value>
      <webElementGuid>c2315315-ca95-4542-97e2-9f60c1dd6357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Criar </value>
      <webElementGuid>efdf2cde-f9ba-4b7b-94e1-54cdaaed0054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empresa-list-grid-header-actionbar&quot;)/div[@class=&quot;ndd-ng-actionbar__item ndd-ng-actionbar__item--pull-right&quot;]/div[@class=&quot;ndd-ng-hide-when-responsive ndd-ng-hide-when-mobile&quot;]/ndd-ng-actionbar-action[1]/div[@class=&quot;ndd-ng-actionbar__action&quot;]/button[@id=&quot;empresa-list-actions-create&quot;]</value>
      <webElementGuid>4491c8d0-144e-475c-b8d8-0ccd92737aac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='empresa-list-actions-create']</value>
      <webElementGuid>294aa65b-2855-438c-9915-9509e7a7e4f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='empresa-list-grid-header-actionbar']/div/div/ndd-ng-actionbar-action/div/button</value>
      <webElementGuid>badf1772-b5d7-4991-afc1-c43a4db20109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NFSe'])[1]/following::button[1]</value>
      <webElementGuid>67071ad1-b05e-4569-89a5-f897c396874f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NFe'])[1]/following::button[2]</value>
      <webElementGuid>05a2cd98-bae6-485f-a92e-3be7205e11be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Excluir'])[1]/preceding::button[1]</value>
      <webElementGuid>2067e337-f572-41ce-97cb-747babff49c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Abrir'])[1]/preceding::button[2]</value>
      <webElementGuid>1ed7b58a-8e8b-442a-9333-6f66edb35c93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Criar']/parent::*</value>
      <webElementGuid>46e51bdd-2f77-43dd-8b17-22f6cb1a203c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>1bba1e29-62ec-4e37-9f21-276ab4de9e2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'empresa-list-actions-create' and @title = 'Criar' and (text() = 'Criar ' or . = 'Criar ')]</value>
      <webElementGuid>5584d108-c06e-44d5-aa81-99744c9bc883</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
