<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Salvar</name>
   <tag></tag>
   <elementGuidId>8cd480c0-b3de-4c08-9acf-14de1cbd9a58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ndd-ng-button-save&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ndd-ng-button-save-open</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6edb08ac-5e71-4e3d-9af7-a0d005b03297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ndd-ng-button ndd-ng-button--medium ndd-ng-button--primary</value>
      <webElementGuid>a620eed2-b40f-4f80-a2c5-df2ab2c24c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ndd-ng-button-save-open</value>
      <webElementGuid>a0e1d00d-6a77-425b-b0ea-d16c31ad9746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>09a8d8c8-9e32-4322-a524-6463fbab81c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ndd-ng-button-save-open</value>
      <webElementGuid>a6983a3b-b081-4b5e-8270-cd27aa7d72cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Salvar e abrir </value>
      <webElementGuid>78584a2a-0652-4970-9b30-62e20d1454fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ndd-ng-button-save-open&quot;)</value>
      <webElementGuid>0608f803-fce8-4c66-81e4-d32ad7a31483</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ndd-ng-button-save-open']</value>
      <webElementGuid>e2b6f191-19ac-4324-b872-32b4941ab259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='configuracao']/configuracao-app/div/ng-component/ng-component/ndd-ng-spinner/fieldset/div[2]/ndd-ng-button[2]/button</value>
      <webElementGuid>7ff3db2d-b810-46ae-bef9-d3c6e2dd3d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salvar'])[1]/following::button[1]</value>
      <webElementGuid>bfc205ed-f053-4db2-9008-52dcad259f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logomarca'])[1]/following::button[2]</value>
      <webElementGuid>d771441c-89b3-44ef-8f5d-677b929039d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salvar e criar'])[1]/preceding::button[1]</value>
      <webElementGuid>d34f55d1-7f72-4815-bd1d-daaf118df215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[2]/preceding::button[2]</value>
      <webElementGuid>3bb0304e-d44b-44ed-9274-8900bf34ab89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Salvar e abrir']/parent::*</value>
      <webElementGuid>9bc33fd0-9e88-41bc-8326-81b5f275c1a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ndd-ng-button[2]/button</value>
      <webElementGuid>32debe60-105a-4af9-b4f2-da596c27155b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ndd-ng-button-save-open' and @type = 'submit' and @name = 'ndd-ng-button-save-open' and (text() = ' Salvar e abrir ' or . = ' Salvar e abrir ')]</value>
      <webElementGuid>f8a4ade1-56b2-4be2-907b-808eb478713d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
