<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Empresa</name>
   <tag></tag>
   <elementGuidId>db7cf710-ff52-4671-8acd-2511568d91fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='suboption-configuracao-empresa']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#suboption-configuracao-empresa > div.ndd-ng-sidebar__item__content > div.ndd-ng-sidebar__item__text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8af7d669-c1e0-4484-b5b4-622c607ad990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ndd-ng-sidebar__item__text</value>
      <webElementGuid>d2c55c55-e105-4323-9921-8aec6d677dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Empresa</value>
      <webElementGuid>7c31a632-6737-4227-b887-4d4c5d8bb3ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suboption-configuracao-empresa&quot;)/div[@class=&quot;ndd-ng-sidebar__item__content&quot;]/div[@class=&quot;ndd-ng-sidebar__item__text&quot;]</value>
      <webElementGuid>5657fe7a-49dc-47fe-b7cf-75a2259996fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='suboption-configuracao-empresa']/div/div</value>
      <webElementGuid>8671c848-30f3-4995-89d2-1eeecee50d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ambiente'])[1]/following::div[3]</value>
      <webElementGuid>174350aa-bdaf-4958-9f58-f740d19fae6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Licença'])[1]/following::div[6]</value>
      <webElementGuid>4336ae8b-b8f2-4415-a113-e07a21fbfa6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parceiro Neogrid'])[1]/preceding::div[2]</value>
      <webElementGuid>cdb317fa-5611-4bf7-8558-a0c317b62197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ndd-ng-sidebar-option[4]/li/div[2]/div/ndd-ng-sidebar-option[4]/li/div/div</value>
      <webElementGuid>83eedee2-3ac1-4203-a9b3-cd9c7ee9d738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Empresa' or . = 'Empresa')]</value>
      <webElementGuid>c9dfbe91-4576-42a7-b84c-c6a3abe66f69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
