<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Inscrio Estadual  Inscrio Municipal</name>
   <tag></tag>
   <elementGuidId>675d3d22-dcf8-4bb1-8162-d770b3fe0d54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='configuracao']/configuracao-app/div/ng-component/ng-component/ndd-ng-spinner/fieldset/div/empresa-create-form/form/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>043ef2a6-2623-4412-bf25-f9e9be282421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>3bab76f9-c2f2-42c4-95e6-b1522dadda66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Inscrição Estadual  Inscrição Municipal </value>
      <webElementGuid>4fd69b58-c913-4791-a0f7-0d227c887d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;configuracao&quot;)/configuracao-app[1]/div[@class=&quot;ndd-container__content&quot;]/ng-component[1]/ng-component[1]/ndd-ng-spinner[1]/fieldset[@class=&quot;ndd-ng-spinner&quot;]/div[@class=&quot;container-fluid feature-view__content&quot;]/empresa-create-form[1]/form[@class=&quot;ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;row&quot;]</value>
      <webElementGuid>cc8045c1-7bec-4f64-a7bd-cd7eb8080195</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='configuracao']/configuracao-app/div/ng-component/ng-component/ndd-ng-spinner/fieldset/div/empresa-create-form/form/div[4]</value>
      <webElementGuid>d53ea5b6-f6bb-4054-9c1b-8f7d6fae9478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::div[3]</value>
      <webElementGuid>7ca095c4-04d3-47f3-8c83-53b517dd262d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[4]</value>
      <webElementGuid>4a568c3b-7acd-49df-8e10-b73812d1af6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Inscrição Estadual  Inscrição Municipal ' or . = ' Inscrição Estadual  Inscrição Municipal ')]</value>
      <webElementGuid>a451a3cf-aa14-4d49-9d08-13140412123b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
