<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__cnpj</name>
   <tag></tag>
   <elementGuidId>6ca242f8-d455-4cd4-a985-04a283f784c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cnpj']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cnpj</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9ee324b-70cd-4c4c-b656-43b5b2acf026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>62d8c97c-564b-4bfe-981e-f96c96fe8738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ndd-ng-form-control ndd-ng-form-control--invalid ng-invalid ng-touched ng-pristine</value>
      <webElementGuid>7f0c6433-242e-4e27-a323-a9f3f6316415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cnpj</value>
      <webElementGuid>035b971d-c304-4593-adac-9df00ca0517f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dbfae9f5-fe4d-435a-a063-45d9030cf196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cnpj&quot;)</value>
      <webElementGuid>8cb83876-0d6d-4950-abb9-644ee5337542</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cnpj']</value>
      <webElementGuid>42c8017f-9d87-4277-891c-e1083a1180ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='configuracao']/configuracao-app/div/ng-component/ng-component/ndd-ng-spinner/fieldset/div/empresa-create-form/form/div[3]/div/ndd-ng-input/div/input</value>
      <webElementGuid>a18f9ae9-7a78-41ae-b3bb-b67c77fc49d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ndd-ng-input/div/input</value>
      <webElementGuid>8fda4fec-121e-4402-8531-e0eaa965fd59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cnpj' and @type = 'text']</value>
      <webElementGuid>cd905a5d-9ba2-49e3-aaac-e8d260a9f184</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
