<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__apelidoEmpresa</name>
   <tag></tag>
   <elementGuidId>ac4f1c17-e95c-497e-bf33-e6e7c5dd1f18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='apelidoEmpresa']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#apelidoEmpresa</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92635695-d4dc-403f-b0f0-45dfcca4746f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6166a50d-ac47-4a8e-97fa-43c99339843d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ndd-ng-form-control ndd-ng-form-input--has-value ng-invalid ng-untouched ng-dirty</value>
      <webElementGuid>8a94fb54-065c-4c88-a0ec-c0dd8ef7ebea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apelidoEmpresa</value>
      <webElementGuid>6ea761d0-f262-4bf5-ae14-70bcb79332f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>31372d98-7935-4ef3-a06d-76e317607c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apelidoEmpresa&quot;)</value>
      <webElementGuid>a7c350f7-2f4a-4540-98a0-36753c6d1aaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='apelidoEmpresa']</value>
      <webElementGuid>7e9bb568-49ae-417c-baec-dd5dc512de68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='configuracao']/configuracao-app/div/ng-component/ng-component/ndd-ng-spinner/fieldset/div/empresa-create-form/form/div[2]/div/ndd-ng-input/div/input</value>
      <webElementGuid>218d4e50-cf17-4f92-8cd0-69def22883e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ndd-ng-input/div/input</value>
      <webElementGuid>aec94585-fc93-4d4c-9325-5eb9f0b41b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'apelidoEmpresa' and @type = 'text']</value>
      <webElementGuid>66fda3db-6805-4e31-bde4-89f2ec7796e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
