<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Inscrio Municipal_inscricaoMunicipal</name>
   <tag></tag>
   <elementGuidId>ce74d67b-b263-449e-b91e-cce94ba530f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inscricaoMunicipal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inscricaoMunicipal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86d8c960-4a20-4ea9-9773-9f9bbba41b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a6d4bd64-139f-490c-9a1b-82a51a04b6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ndd-ng-form-control ng-valid ng-untouched ng-pristine</value>
      <webElementGuid>86a0ef48-2c98-4a65-a13d-d3846f6691cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inscricaoMunicipal</value>
      <webElementGuid>cd9d5011-e4fb-44b9-82bb-9d1ea808fe74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cb8058d6-0ba9-4b73-a188-e7d244a5a241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inscricaoMunicipal&quot;)</value>
      <webElementGuid>dd6559b1-fefe-4787-b259-867d28be7239</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inscricaoMunicipal']</value>
      <webElementGuid>00640ac6-0149-47f9-b48d-fd082583610a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='configuracao']/configuracao-app/div/ng-component/ng-component/ndd-ng-spinner/fieldset/div/empresa-create-form/form/div[4]/div[2]/ndd-ng-input/div/input</value>
      <webElementGuid>31e5c790-ccb4-464c-8043-3eb93f88664f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ndd-ng-input/div/input</value>
      <webElementGuid>19fc9b6b-ea58-406e-a336-5add8e0976bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inscricaoMunicipal' and @type = 'text']</value>
      <webElementGuid>d92b37d2-dbfb-4072-9185-eaff12879a0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
