<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__razaoSocial</name>
   <tag></tag>
   <elementGuidId>97ec4af4-9d65-454c-a930-882c528d2527</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='razaoSocial']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ndd-form-group > #razaoSocial</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cadbab39-1745-44f9-bb65-50acdf72f00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9f61a439-d57e-4562-9c7c-643b91a4ebae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ndd-ng-form-control ng-invalid ng-untouched ng-pristine</value>
      <webElementGuid>65ea6734-2307-45ee-a201-52f3a76e3739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>razaoSocial</value>
      <webElementGuid>3cf27862-6845-4b60-8853-5e8d81258c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5d2a851f-6ab9-497f-8d26-ccf5b097ad7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;configuracao&quot;)/configuracao-app[1]/div[@class=&quot;ndd-container__content&quot;]/ng-component[1]/ng-component[1]/ndd-ng-spinner[1]/fieldset[@class=&quot;ndd-ng-spinner&quot;]/div[@class=&quot;container-fluid feature-view__content&quot;]/empresa-create-form[1]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/ndd-ng-input[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;ndd-form-group&quot;]/input[@id=&quot;razaoSocial&quot;]</value>
      <webElementGuid>faf172bd-013b-436f-af00-31aeb4a98d74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='razaoSocial']</value>
      <webElementGuid>14110be3-4c43-4932-bb15-0a2b4ca5a600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='configuracao']/configuracao-app/div/ng-component/ng-component/ndd-ng-spinner/fieldset/div/empresa-create-form/form/div/div/ndd-ng-input/div/input</value>
      <webElementGuid>5e613746-1c55-48a0-b38d-68b653be5066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ndd-ng-input/div/input</value>
      <webElementGuid>4182470e-d64c-495f-9311-c89c78c645fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'razaoSocial' and @type = 'text']</value>
      <webElementGuid>58e8558c-26f8-4111-b1b5-22f583302be7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
