<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Ambiente Desenvolvimento  Testes</name>
   <tag></tag>
   <elementGuidId>878508d8-93a2-40c0-bde1-f59709373316</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='a55787dd-4dbe-4278-ae97-e9dfa151f7f1-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a55787dd-4dbe-4278-ae97-e9dfa151f7f1-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>fadddec1-f745-433c-ba6e-22e10e191d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f308c084-4f71-41ad-9d2e-6a1c074f42df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-focused k-state-selected</value>
      <webElementGuid>01f94e32-565a-4c77-b2b9-606d091877e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a55787dd-4dbe-4278-ae97-e9dfa151f7f1-0</value>
      <webElementGuid>1fedcdd2-b78a-439d-af94-68b39a0b351c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>7fbc2230-7417-43b5-af72-b1a261080a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>042088ed-6b58-4b37-80ab-25ea78e114fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ambiente Desenvolvimento / Testes</value>
      <webElementGuid>e5bf52f9-236b-42a6-934c-8eefb2a05946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a55787dd-4dbe-4278-ae97-e9dfa151f7f1-0&quot;)</value>
      <webElementGuid>6960c6f5-b9a9-4ad6-b38a-9d49201ce6af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='a55787dd-4dbe-4278-ae97-e9dfa151f7f1-0']</value>
      <webElementGuid>9c852460-9526-401f-9cba-7fb7bde768bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ae22e228-6993-4f59-af47-b2c461f89af0']/li[2]</value>
      <webElementGuid>885e21d1-6950-4348-9bbf-7ae2a66b6ee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selecione um ambiente'])[1]/following::li[1]</value>
      <webElementGuid>30b97ebd-4e5a-462f-ac6b-60dd60f379f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[2]/following::li[2]</value>
      <webElementGuid>01c64ca1-3d6f-40cf-bd63-936acb3607f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ambiente de teste Elcio'])[1]/preceding::li[1]</value>
      <webElementGuid>5d653217-feca-41e2-9bb0-7d91ce66a438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ambiente Patii'])[1]/preceding::li[2]</value>
      <webElementGuid>788a4d8c-57bd-4a10-82c5-fbdccccb2d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]</value>
      <webElementGuid>991c5afc-1121-4162-aed9-7736d62c0460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'a55787dd-4dbe-4278-ae97-e9dfa151f7f1-0' and (text() = 'Ambiente Desenvolvimento / Testes' or . = 'Ambiente Desenvolvimento / Testes')]</value>
      <webElementGuid>9f699d6e-e1bd-403f-a77f-2f2963bf584c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
