<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Lages</name>
   <tag></tag>
   <elementGuidId>ca333f1f-a901-43dd-8065-71fcdabb5a0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='f8e4c0bf-3dfa-43ad-9522-198600e88d31-142']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f8e4c0bf-3dfa-43ad-9522-198600e88d31-142</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c1afb0a9-6078-4886-8e92-60a883e510fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e0b058da-9125-486d-9047-fd57322b2051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item</value>
      <webElementGuid>62afaef3-6658-4ddd-9d0b-c68e49c1ba73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f8e4c0bf-3dfa-43ad-9522-198600e88d31-142</value>
      <webElementGuid>7774347e-5957-4c8e-b48a-918a0c2c0a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>561fd307-20f7-41c8-9c81-4028806f8056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>142</value>
      <webElementGuid>6a577661-dae7-4e3a-b81d-f7cdccae1d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lages</value>
      <webElementGuid>77fc2ed8-7d3b-42a1-be23-7387a64cdfad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f8e4c0bf-3dfa-43ad-9522-198600e88d31-142&quot;)</value>
      <webElementGuid>350cef16-cbfb-4735-a3f5-a7c48a418e49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='f8e4c0bf-3dfa-43ad-9522-198600e88d31-142']</value>
      <webElementGuid>48146643-a003-4b55-a281-3162e3484692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='f652c547-8be1-4b9d-be67-7029a77483cf']/li[143]</value>
      <webElementGuid>31d8716b-1dd2-45ed-9833-e10882e3389b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lacerdópolis'])[2]/following::li[1]</value>
      <webElementGuid>d4466853-e4b6-4fcd-bae5-6e644c510399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jupiá'])[1]/following::li[2]</value>
      <webElementGuid>b902279f-eb17-4289-8fe1-a0b9718fbbba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laguna'])[1]/preceding::li[1]</value>
      <webElementGuid>7566fbf9-4ffd-4c7d-bf84-963f44381d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lajeado Grande'])[1]/preceding::li[2]</value>
      <webElementGuid>ac5293cb-ae86-49ea-a134-ab2d00401da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[143]</value>
      <webElementGuid>fe0dcd7c-b290-436a-9ea9-f0a3e8919349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'f8e4c0bf-3dfa-43ad-9522-198600e88d31-142' and (text() = 'Lages' or . = 'Lages')]</value>
      <webElementGuid>0a3952c3-edb0-48b6-bf7f-15cf0153cee3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
