<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Santa Catarina</name>
   <tag></tag>
   <elementGuidId>cc0be999-9a42-4d5d-a58e-449ca8f7fa96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='79ca7384-1803-412c-860a-49c52b54ff8e-23']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#79ca7384-1803-412c-860a-49c52b54ff8e-23</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ca06cd00-178a-479a-8e1f-f2137029cd7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>6346b400-61c0-4225-84a0-1d5380b9f4bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-focused k-state-selected</value>
      <webElementGuid>24968343-027c-419b-9d21-ed09476970d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>79ca7384-1803-412c-860a-49c52b54ff8e-23</value>
      <webElementGuid>737f7440-9b11-458d-a6ed-b2b0b54abab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1046964b-544e-4f94-af9f-1d519936bfa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>23</value>
      <webElementGuid>85f53303-a555-4c30-8ed1-5839bd4f9dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Santa Catarina</value>
      <webElementGuid>44326ddb-2b42-4ac8-8605-c6a4a5b7b1d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;79ca7384-1803-412c-860a-49c52b54ff8e-23&quot;)</value>
      <webElementGuid>f27992b5-014b-49d3-abe4-b2db4aa504a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='79ca7384-1803-412c-860a-49c52b54ff8e-23']</value>
      <webElementGuid>ef81dc83-142a-4a09-8e61-f6d6505b3e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='9b1f33f2-1c4f-412d-81f0-e0e1b56722af']/li[24]</value>
      <webElementGuid>d1fae7b2-0241-4daa-b742-d20eb7e51084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roraima'])[1]/following::li[1]</value>
      <webElementGuid>34bc0642-ec76-4d2b-b6c4-a7ffa371e315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rondônia'])[1]/following::li[2]</value>
      <webElementGuid>51a2a913-429f-4469-a797-a73282778738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='São Paulo'])[1]/preceding::li[1]</value>
      <webElementGuid>1bc4f6dd-804c-4679-b6f4-b6d3e3f02bb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sergipe'])[1]/preceding::li[2]</value>
      <webElementGuid>2d7e2d35-7987-4c30-912c-9f2844a146db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[24]</value>
      <webElementGuid>52c50a7d-c777-45d7-aa9c-b92b37a69b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '79ca7384-1803-412c-860a-49c52b54ff8e-23' and (text() = 'Santa Catarina' or . = 'Santa Catarina')]</value>
      <webElementGuid>828b6f22-7aea-4d0d-8e6d-4c30c3c0fa2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
