<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pesquisar</name>
   <tag></tag>
   <elementGuidId>942b5b0b-7a6e-461b-b067-920da754be7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;empresa-list-grid-header-actionbar&quot;]/div[2]/ndd-ng-searchbar/div/span/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
