<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Abdon Batista</name>
   <tag></tag>
   <elementGuidId>3fbdcd4e-76f5-421d-b40f-08960217879e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='921ec451-2137-4f63-9fcd-15e1487c2ec5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#921ec451-2137-4f63-9fcd-15e1487c2ec5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>319e6426-9d75-41f0-b2e9-e502fa171d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>53492a1b-e87e-4391-823b-da32610e8934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>b6069c2c-a899-42ab-909e-111e4ef16a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>921ec451-2137-4f63-9fcd-15e1487c2ec5</value>
      <webElementGuid>2a1a6eda-9c99-4edd-843f-a320fe6b5e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Abdon Batista</value>
      <webElementGuid>17ead60c-d091-44bb-bd24-203bcd8a5391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;921ec451-2137-4f63-9fcd-15e1487c2ec5&quot;)</value>
      <webElementGuid>ce755004-9d77-4f80-af7d-bac2f90194c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='921ec451-2137-4f63-9fcd-15e1487c2ec5']</value>
      <webElementGuid>b5b4feaf-7880-4e62-ad55-d5f71b758d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-c27a2e86-1fb3-4cdb-81d1-b177ea3f3412']/span</value>
      <webElementGuid>492baf08-1a37-4ab5-becf-86ed3747f565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cidade'])[3]/following::span[2]</value>
      <webElementGuid>cb77c10a-f953-4536-9b1e-fcaa438e0427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Santa Catarina'])[1]/following::span[4]</value>
      <webElementGuid>4448da3b-7836-43c9-bf25-7501722a41be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ambiente'])[1]/preceding::span[3]</value>
      <webElementGuid>f638c740-630e-47cc-80e8-5232e1c6922e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ambiente Desenvolvimento / Testes'])[1]/preceding::span[3]</value>
      <webElementGuid>0a6b659c-54f5-47b7-9ddd-a6be4693b918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Abdon Batista']/parent::*</value>
      <webElementGuid>44e88286-ef37-4779-bf02-88ec76344374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ndd-ng-select/div/kendo-dropdownlist/span/span</value>
      <webElementGuid>101ffe48-4c98-42bd-9baf-5d6f13157757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = '921ec451-2137-4f63-9fcd-15e1487c2ec5' and (text() = 'Abdon Batista' or . = 'Abdon Batista')]</value>
      <webElementGuid>c988ed04-6f6e-4b6f-ac3a-c7ea684d417f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
