<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Segmentos todos templates_k-icon k-i-arrow-s</name>
   <tag></tag>
   <elementGuidId>c0927688-00f1-4b9d-9cfa-d9a340a7e9c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='k-f7a0b1af-176a-4ee8-956c-b17a1495bcad']/span[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#k-f7a0b1af-176a-4ee8-956c-b17a1495bcad > span.k-select > span.k-icon.k-i-arrow-s</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6cb8b942-3ad1-4d44-8279-2a52258ea401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>6a267a27-02ac-4fb0-8456-8ab7585f8f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-icon k-i-arrow-s</value>
      <webElementGuid>8d5fb57b-daf3-4f1f-8755-8213e645f959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-f7a0b1af-176a-4ee8-956c-b17a1495bcad&quot;)/span[@class=&quot;k-select&quot;]/span[@class=&quot;k-icon k-i-arrow-s&quot;]</value>
      <webElementGuid>efc7a45e-83b3-49e9-9198-79b18f462961</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-f7a0b1af-176a-4ee8-956c-b17a1495bcad']/span[2]/span</value>
      <webElementGuid>6f154eda-0f4d-48bd-9727-8795540b2b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/ndd-ng-select/div/kendo-dropdownlist/span/span[2]/span</value>
      <webElementGuid>c0037bbc-4677-4763-b5b4-9592c556ea04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
