<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_estado_select</name>
   <tag></tag>
   <elementGuidId>51567364-5edc-426e-acc3-04c2ff4f937a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ec5eb132-c5f0-44aa-ba80-4c03fabc4353&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#k-943f5f65-f16b-4972-8b02-90695675847e > span.k-select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>61870f85-026e-4a29-89b6-0ff379006e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>4afa6a92-8366-430e-b59a-fa56c5c29240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-select</value>
      <webElementGuid>6ee037cb-bca1-48d5-a5a0-6125c49b4ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;k-943f5f65-f16b-4972-8b02-90695675847e&quot;)/span[@class=&quot;k-select&quot;]</value>
      <webElementGuid>97f0040b-3944-44cf-9695-fc51263b93fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-943f5f65-f16b-4972-8b02-90695675847e']/span[2]</value>
      <webElementGuid>75f8ef26-1c10-45a4-9ebc-094cdf740952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acre'])[1]/following::span[1]</value>
      <webElementGuid>d9b8466d-285d-48d5-9027-70a51f42ae9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UF'])[3]/following::span[3]</value>
      <webElementGuid>a63eef32-990c-414f-8d29-7f7cd0c41024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cidade'])[3]/preceding::span[2]</value>
      <webElementGuid>b55a438b-622b-4422-9447-a196f94843e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acrelândia'])[1]/preceding::span[2]</value>
      <webElementGuid>47d1e36e-3806-4412-9155-3d2a6cf08ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/kendo-dropdownlist/span/span[2]</value>
      <webElementGuid>2760b00f-37d4-4f51-87b5-f65d32613d13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
